function C_jac = C_jac_fun(in1)
%C_JAC_FUN
%    C_JAC = C_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 21:13:30

C_jac = reshape([0.0,0.0],[1, 1, 2]);
