function fric = fric_fun(in1)
%FRIC_FUN
%    FRIC = FRIC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 21:13:30

qdot = in1(2,:);
fric = qdot;
