function M_jac = M_jac_fun(in1)
%M_JAC_FUN
%    M_JAC = M_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 21:13:30

M_jac = reshape([0.0,0.0],[1, 1, 2]);
