function phi_jac = phi_jac_fun(in1)
%PHI_JAC_FUN
%    PHI_JAC = PHI_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 21:13:30

q = in1(1,:);
phi_jac = [sin(q).*(-4.9e1./5.0),0.0];
