function phi = phi_fun(in1)
%PHI_FUN
%    PHI = PHI_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 21:13:30

q = in1(1,:);
phi = cos(q).*(4.9e1./5.0);
