function tip_jac = tip_jac_fun(in1)
%TIP_JAC_FUN
%    TIP_JAC = TIP_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 21:13:43

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1+x2;
t3 = sin(t2);
t4 = cos(t2);
tip_jac = reshape([-t3-sin(x1),t4+cos(x1),-t3,t4],[2, 2]);
