function V_jac = V_jac_fun(in1)
%V_JAC_FUN
%    V_JAC = V_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    19-May-2015 01:22:03

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1+x2;
t3 = cos(t2);
t4 = t3.*(1.0./2.0e1);
V_jac = [t4+cos(x1).*(3.0./2.0e1),t4];
