function fric_jac = fric_jac_fun(in1)
%FRIC_JAC_FUN
%    FRIC_JAC = FRIC_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    06-Mar-2015 16:41:22

fric_jac = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0],[3, 6]);
