function M = M_fun(in1)
%M_FUN
%    M = M_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    06-Mar-2015 16:41:21

x2 = in1(2,:);
x3 = in1(3,:);
t2 = x2+x3;
t3 = cos(t2);
t4 = cos(x2);
t5 = cos(x3);
t6 = t5.*(9.0./1.25e2);
t7 = t3.*(9.0./2.0e2);
t8 = t4.*(1.4e1./2.5e1);
t9 = t6+t7+t8+4.77e2./8.0e2;
t10 = t5.*(9.0./2.5e2);
t11 = t7+t10+2.025e-2;
t12 = t10+2.025e-2;
M = reshape([t3.*(9.0./1.0e2)+t4.*(2.8e1./2.5e1)+t6+2.44625,t9,t11,t9,t6+4.77e2./8.0e2,t12,t11,t12,2.025e-2],[3, 3]);
