function phi_jac = phi_jac_fun(in1)
%PHI_JAC_FUN
%    PHI_JAC = PHI_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    06-Mar-2015 16:41:22

phi_jac = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3, 6]);
