function polar2Cartesian_jac = polar2Cartesian_jac_fun(in1)
%POLAR2CARTESIAN_JAC_FUN
%    POLAR2CARTESIAN_JAC = POLAR2CARTESIAN_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    06-Mar-2015 16:41:23

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = x1+x2+x3;
t3 = sin(t2);
t4 = x1+x2;
t5 = sin(t4);
t6 = cos(t2);
t7 = t6.*(3.0./1.0e1);
t8 = cos(t4);
t9 = t8.*(4.0./5.0);
polar2Cartesian_jac = reshape([t3.*(-3.0./1.0e1)-t5.*(4.0./5.0)-sin(x1),t7+t9+cos(x1),t3.*(-3.0./1.0e1)-t5.*(4.0./5.0),t7+t9,t3.*(-3.0./1.0e1),t7,0.0,0.0,0.0,0.0,0.0,0.0],[2, 6]);
