function polar2Cartesian = polar2Cartesian_fun(in1)
%POLAR2CARTESIAN_FUN
%    POLAR2CARTESIAN = POLAR2CARTESIAN_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    06-Mar-2015 16:41:22

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = x1+x2+x3;
t3 = x1+x2;
polar2Cartesian = [cos(t2).*(3.0./1.0e1)+cos(t3).*(4.0./5.0)+cos(x1);sin(t2).*(3.0./1.0e1)+sin(t3).*(4.0./5.0)+sin(x1)];
