% calculate the vector field
% inputs: value of states: x
%         input to the system: u
% use the following functions generated by Symb_lagrange_solver.m
% M_fun.m
% C_fun.m
% phi_fun.m
% fric_fun.m

function qddot = qddot_fun(x,u)
    
    % get the dimension of the system
    n = length(x)/2;
    % q = x(1:n);
    qdot = x((n+1):(2*n));
    
    % intermidiate steps
    M = M_fun(x);
    C = C_fun(x);
    phi = phi_fun(x);
    fric = fric_fun(x);
    
    % output
    qddot = M\( - C*qdot - phi + u - fric);
end