function reach_error2_jac = reach_error2_jac_fun(in1,in2)
%REACH_ERROR2_JAC_FUN
%    REACH_ERROR2_JAC = REACH_ERROR2_JAC_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    06-Mar-2015 16:41:27

target1 = in2(1,:);
target2 = in2(2,:);
target3 = in2(3,:);
target4 = in2(4,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
t2 = x1+x2;
t3 = x1+x2+x3;
t4 = sin(t3);
t5 = t4.*target1.*(3.0./5.0);
t6 = cos(t2);
t7 = sin(t2);
t8 = t7.*target1.*(8.0./5.0);
t9 = cos(t3);
t10 = x2+x3;
t11 = sin(t10);
t12 = x7+x8;
t13 = x7+x8+x9;
t14 = sin(t13);
t15 = t14.*target3.*(3.0./5.0);
t16 = cos(t12);
t17 = sin(t12);
t18 = t17.*target3.*(8.0./5.0);
t19 = cos(t13);
t20 = x8+x9;
t21 = sin(t20);
reach_error2_jac = [t5+t8-t6.*target2.*(8.0./5.0)-t9.*target2.*(3.0./5.0)-target2.*cos(x1).*2.0+target1.*sin(x1).*2.0;t5+t8-t11.*(3.0./5.0)-sin(x2).*(8.0./5.0)-t6.*target2.*(8.0./5.0)-t9.*target2.*(3.0./5.0);t5-t11.*(3.0./5.0)-sin(x3).*(1.2e1./2.5e1)-t9.*target2.*(3.0./5.0);0.0;0.0;0.0;t15+t18-t16.*target4.*(8.0./5.0)-t19.*target4.*(3.0./5.0)-target4.*cos(x7).*2.0+target3.*sin(x7).*2.0;t15+t18-t21.*(3.0./5.0)-sin(x8).*(8.0./5.0)-t16.*target4.*(8.0./5.0)-t19.*target4.*(3.0./5.0);t15-t21.*(3.0./5.0)-sin(x9).*(1.2e1./2.5e1)-t19.*target4.*(3.0./5.0);0.0;0.0;0.0];
