function reach_error_jac = reach_error_jac_fun(in1,in2)
%REACH_ERROR_JAC_FUN
%    REACH_ERROR_JAC = REACH_ERROR_JAC_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    06-Mar-2015 16:41:23

target1 = in2(1,:);
target2 = in2(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = x1+x2+x3;
t3 = cos(t2);
t4 = t3.*(3.0./1.0e1);
t5 = x1+x2;
t6 = cos(t5);
t7 = t6.*(4.0./5.0);
t8 = cos(x1);
t9 = t4+t7+t8-target1;
t10 = sin(t2);
t11 = t10.*(3.0./1.0e1);
t12 = sin(t5);
t13 = t12.*(4.0./5.0);
t14 = sin(x1);
t15 = t11+t13+t14-target2;
t16 = abs(t9);
t17 = sign(t9);
t18 = abs(t15);
t19 = sign(t15);
reach_error_jac = [t18.*t19.*(t4+t7+t8).*2.0-t16.*t17.*(t11+t13+t14).*2.0,t18.*t19.*(t4+t7).*2.0-t16.*t17.*(t11+t13).*2.0,t3.*t18.*t19.*(3.0./5.0)-t10.*t16.*t17.*(3.0./5.0),0.0,0.0,0.0];
