function reach_error2 = reach_error2_fun(in1,in2)
%REACH_ERROR2_FUN
%    REACH_ERROR2 = REACH_ERROR2_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    06-Mar-2015 16:41:27

target1 = in2(1,:);
target2 = in2(2,:);
target3 = in2(3,:);
target4 = in2(4,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
t4 = x1+x2+x3;
t5 = x1+x2;
t2 = abs(-target1+cos(t4).*(3.0./1.0e1)+cos(t5).*(4.0./5.0)+cos(x1));
t7 = x7+x8+x9;
t8 = x7+x8;
t3 = abs(-target3+cos(t7).*(3.0./1.0e1)+cos(t8).*(4.0./5.0)+cos(x7));
t6 = abs(-target2+sin(t4).*(3.0./1.0e1)+sin(t5).*(4.0./5.0)+sin(x1));
t9 = abs(-target4+sin(t7).*(3.0./1.0e1)+sin(t8).*(4.0./5.0)+sin(x7));
reach_error2 = t2.^2+t3.^2+t6.^2+t9.^2;
