function C_syms = C_fun(x1,x2,x3,x4)
%C_FUN
%    C_SYMS = C_FUN(X1,X2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:52:06

t2 = sin(x2);
C_syms = reshape([t2.*x4.*(-1.0./4.0),t2.*(1.0./8.0),t2.*x4.*(-1.0./8.0),0.0],[2, 2]);
