function D_syms = D_fun(x1,x2,x3,x4)
%D_FUN
%    D_SYMS = D_FUN(X1,X2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:52:06

t2 = cos(x2);
t3 = t2.*(1.0./8.0);
t4 = t3+1.0./2.4e1;
D_syms = reshape([t2.*(1.0./4.0)+7.0./8.0,t4,t4,1.0./2.4e1],[2, 2]);
