function polar2Cartesian_jac_syms = polar2Cartesian_jac_fun(x1,x2)
%POLAR2CARTESIAN_JAC_FUN
%    POLAR2CARTESIAN_JAC_SYMS = POLAR2CARTESIAN_JAC_FUN(X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:52:09

t2 = x1+x2;
t3 = sin(t2);
t4 = cos(t2);
t5 = t4.*(1.0./2.0);
polar2Cartesian_jac_syms = reshape([t3.*(-1.0./2.0)-sin(x1),t5+cos(x1),t3.*(-1.0./2.0),t5],[2, 2]);
