function polar2Cartesian_syms = polar2Cartesian_fun(x1,x2)
%POLAR2CARTESIAN_FUN
%    POLAR2CARTESIAN_SYMS = POLAR2CARTESIAN_FUN(X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:52:09

t2 = x1+x2;
polar2Cartesian_syms = [cos(t2).*(1.0./2.0)+cos(x1);sin(t2).*(1.0./2.0)+sin(x1)];
