function V_jac_syms = V_jac_fun(x1,x2,x3,x4)
%V_JAC_FUN
%    V_JAC_SYMS = V_JAC_FUN(X1,X2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:52:06

t2 = x1+x2;
t3 = cos(t2);
t4 = t3.*(5.0./4.0);
V_jac_syms = [t4+cos(x1).*1.0e1,t4];
