function C = C_fun(in1)
%C_FUN
%    C = C_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:54

x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = sin(x2);
C = reshape([t2.*x4.*(-1.0./2.0),t2.*x3.*(1.0./2.0),t2.*(x3+x4).*(-1.0./2.0),0.0],[2, 2]);
