function C_jac = C_jac_fun(in1)
%C_JAC_FUN
%    C_JAC = C_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:55

x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x2);
t3 = sin(x2);
C_jac = reshape([0.0,0.0,0.0,0.0,t2.*x4.*(-1.0./2.0),t2.*x3.*(1.0./2.0),t2.*(x3+x4).*(-1.0./2.0),0.0,0.0,t3.*(1.0./2.0),t3.*(-1.0./2.0),0.0,t3.*(-1.0./2.0),0.0,t3.*(-1.0./2.0),0.0],[2, 2, 4]);
