function fric = fric_fun(in1)
%FRIC_FUN
%    FRIC = FRIC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:55

x3 = in1(3,:);
x4 = in1(4,:);
fric = [x3;x4];
