function fric_jac = fric_jac_fun(in1)
%FRIC_JAC_FUN
%    FRIC_JAC = FRIC_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:55

fric_jac = reshape([0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0],[2, 4]);
