function K2 = K2_fun(in1,in2)
%K2_FUN
%    K2 = K2_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:56

u1 = in2(1,:);
x1 = in1(1,:);
t2 = sin(x1);
t3 = cos(x1);
K2 = (t2.*u1.*(2.0./5.0)-t2.*u1.*1.0./sqrt(t3.*-2.0e1+2.9e1).*2.0)./(t2.*(2.0./5.0)-t2.*1.0./sqrt(t3.*2.0e1+2.9e1).*2.0);
