function K4 = K4_fun(in1,in2)
%K4_FUN
%    K4 = K4_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:56

u3 = in2(3,:);
x2 = in1(2,:);
t2 = cos(x2);
t3 = sin(x2);
K4 = (t2.*u3.*(3.0./2.5e1)-t2.*u3.*1.0./sqrt(t3.*-2.4e1+2.5e1).*(1.2e1./2.5e1))./(t2.*(3.0./2.5e1)-t2.*1.0./sqrt(t3.*2.4e1+2.5e1).*(1.2e1./2.5e1));
