function M = M_fun(in1)
%M_FUN
%    M = M_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:54

x2 = in1(2,:);
t2 = cos(x2);
t3 = t2.*(1.0./2.0);
t4 = t3+1.0./3.0;
M = reshape([t2+5.0./3.0,t4,t4,1.0./3.0],[2, 2]);
