function M_jac = M_jac_fun(in1)
%M_JAC_FUN
%    M_JAC = M_JAC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:55

x2 = in1(2,:);
t2 = sin(x2);
M_jac = reshape([0.0,0.0,0.0,0.0,-t2,t2.*(-1.0./2.0),t2.*(-1.0./2.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2, 2, 4]);
