function phi_jac_u = phi_jac_u_fun(in1,in2)
%PHI_JAC_U_FUN
%    PHI_JAC_U = PHI_JAC_U_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:55

x1 = in1(1,:);
x2 = in1(2,:);
t2 = sin(x1);
t3 = t2.*(2.0./5.0);
t4 = cos(x1);
t5 = cos(x2);
t6 = sin(x2);
phi_jac_u = reshape([t3-t2.*1.0./sqrt(t4.*-2.0e1+2.9e1).*2.0,0.0,-t3+t2.*1.0./sqrt(t4.*2.0e1+2.9e1).*2.0,0.0,0.0,t5.*(-3.0./2.5e1)+t5.*1.0./sqrt(t6.*-2.4e1+2.5e1).*(1.2e1./2.5e1),0.0,t5.*(3.0./2.5e1)-t5.*1.0./sqrt(t6.*2.4e1+2.5e1).*(1.2e1./2.5e1)],[2, 4]);
