function phi = phi_fun(in1,in2)
%PHI_FUN
%    PHI = PHI_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:54

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = sin(x1);
t3 = cos(x1);
t4 = cos(x2);
t5 = sin(x2);
phi = [t2.*u1.*(2.0./5.0)-t2.*u2.*(2.0./5.0)-t2.*u1.*1.0./sqrt(t3.*-2.0e1+2.9e1).*2.0+t2.*u2.*1.0./sqrt(t3.*2.0e1+2.9e1).*2.0;t4.*u3.*(-3.0./2.5e1)+t4.*u4.*(3.0./2.5e1)+t4.*u3.*1.0./sqrt(t5.*-2.4e1+2.5e1).*(1.2e1./2.5e1)-t4.*u4.*1.0./sqrt(t5.*2.4e1+2.5e1).*(1.2e1./2.5e1)];
