function phi_jac_x = phi_jac_x_fun(in1,in2)
%PHI_JAC_X_FUN
%    PHI_JAC_X = PHI_JAC_X_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:55

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = cos(x1);
t3 = sin(x1);
t4 = t3.^2;
t5 = t2.*2.0e1;
t6 = t5+2.9e1;
t7 = sin(x2);
t8 = cos(x2);
t9 = t8.^2;
t10 = t7.*2.4e1;
t11 = t10+2.5e1;
phi_jac_x = reshape([t2.*u1.*(2.0./5.0)-t2.*u2.*(2.0./5.0)+t2.*1.0./sqrt(t6).*u2.*2.0+t4.*1.0./t6.^(3.0./2.0).*u2.*2.0e1-t2.*u1.*1.0./sqrt(-t5+2.9e1).*2.0+t4.*u1.*1.0./(t2.*-2.0e1+2.9e1).^(3.0./2.0).*2.0e1,0.0,0.0,t7.*u3.*(3.0./2.5e1)-t7.*u4.*(3.0./2.5e1)+t7.*1.0./sqrt(t11).*u4.*(1.2e1./2.5e1)+t9.*1.0./t11.^(3.0./2.0).*u4.*(1.44e2./2.5e1)-t7.*u3.*1.0./sqrt(-t10+2.5e1).*(1.2e1./2.5e1)+t9.*u3.*1.0./(t7.*-2.4e1+2.5e1).^(3.0./2.0).*(1.44e2./2.5e1),0.0,0.0,0.0,0.0],[2, 4]);
