function tip = tip_fun(in1)
%TIP_FUN
%    TIP = TIP_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:47:53

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1+x2;
tip = [cos(t2)+cos(x1);sin(t2)+sin(x1)];
