function fric = fric_fun(in1)
%FRIC_FUN
%    FRIC = FRIC_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:48:55

x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
fric = [x4.*(1.0./2.0);x5.*(1.0./2.0);x6.*(1.0./2.0)];
