function M = M_fun(in1)
%M_FUN
%    M = M_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Jan-2016 20:48:54

x2 = in1(2,:);
x3 = in1(3,:);
t2 = x2+x3;
t3 = cos(t2);
t4 = cos(x2);
t5 = cos(x3);
t6 = t5.*(1.0./2.0);
t7 = t3.*(1.0./2.0);
t8 = t4+t6+t7+7.0./4.0;
t9 = t5.*(1.0./4.0);
t10 = t7+t9+3.0./4.0;
t11 = t9+3.0./4.0;
M = reshape([t3+t4.*2.0+t6+9.0./2.0,t8,t10,t8,t6+7.0./4.0,t11,t10,t11,3.0./4.0],[3, 3]);
